"""Add face_detection_events table with tracking support

Revision ID: 75a1393746b7
Revises: 9f3e5a8c2d41
Create Date: 2025-11-28 18:53:30.406226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75a1393746b7'
down_revision: Union[str, None] = '9f3e5a8c2d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_detection_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tracking_id', sa.String(length=255), nullable=False),
    sa.Column('camera_id', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('is_recognized', sa.Boolean(), nullable=True),
    sa.Column('recognition_attempts', sa.Integer(), nullable=True),
    sa.Column('tracking_duration_seconds', sa.Float(), nullable=True),
    sa.Column('is_first_detection', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('worker_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_detection_events_camera_id'), 'face_detection_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_face_detection_events_created_at'), 'face_detection_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_face_detection_events_is_recognized'), 'face_detection_events', ['is_recognized'], unique=False)
    op.create_index(op.f('ix_face_detection_events_subject'), 'face_detection_events', ['subject'], unique=False)
    op.create_index(op.f('ix_face_detection_events_tracking_id'), 'face_detection_events', ['tracking_id'], unique=False)
    op.drop_index('ix_global_settings_setting_key', table_name='global_settings')
    op.drop_table('global_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('setting_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('setting_value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='global_settings_pkey'),
    sa.UniqueConstraint('setting_key', name='global_settings_setting_key_key')
    )
    op.create_index('ix_global_settings_setting_key', 'global_settings', ['setting_key'], unique=True)
    op.drop_index(op.f('ix_face_detection_events_tracking_id'), table_name='face_detection_events')
    op.drop_index(op.f('ix_face_detection_events_subject'), table_name='face_detection_events')
    op.drop_index(op.f('ix_face_detection_events_is_recognized'), table_name='face_detection_events')
    op.drop_index(op.f('ix_face_detection_events_created_at'), table_name='face_detection_events')
    op.drop_index(op.f('ix_face_detection_events_camera_id'), table_name='face_detection_events')
    op.drop_table('face_detection_events')
    # ### end Alembic commands ###
