"""add_motion_detection_to_cameras

Revision ID: 7d0d2b9f3eb8
Revises: 04e72706d361
Create Date: 2025-11-20 15:01:48.555464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0d2b9f3eb8'
down_revision: Union[str, None] = '04e72706d361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('motion_detection_enabled', sa.Boolean(), nullable=True))
    op.add_column('cameras', sa.Column('motion_detection_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'motion_detection_config')
    op.drop_column('cameras', 'motion_detection_enabled')
    # ### end Alembic commands ###
