"""add_person_tracking_models

Revision ID: 88480467c528
Revises: 7d0d2b9f3eb8
Create Date: 2025-11-27 00:35:04.079326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88480467c528'
down_revision: Union[str, None] = '7d0d2b9f3eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('camera_id', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('detection_confidence', sa.Float(), nullable=False),
    sa.Column('is_new_person', sa.Boolean(), nullable=True),
    sa.Column('is_new_at_camera', sa.Boolean(), nullable=True),
    sa.Column('dwell_time_seconds', sa.Float(), nullable=True),
    sa.Column('other_cameras', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('alert_sent', sa.Boolean(), nullable=True),
    sa.Column('alert_sent_at', sa.DateTime(), nullable=True),
    sa.Column('alert_channels', sa.JSON(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('worker_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_events_acknowledged'), 'person_events', ['acknowledged'], unique=False)
    op.create_index(op.f('ix_person_events_camera_id'), 'person_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_person_events_created_at'), 'person_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_person_events_profile_id'), 'person_events', ['profile_id'], unique=False)
    op.create_index(op.f('ix_person_events_subject'), 'person_events', ['subject'], unique=False)
    op.create_table('watchlist_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('watchlist_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('added_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('webhook_deliveries')
    op.drop_table('watchlist_profiles')
    op.add_column('profiles', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('face_encodings', sa.JSON(), nullable=True))
    op.add_column('profiles', sa.Column('auto_created', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('alert_on_recognition', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('total_detections', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    op.add_column('profiles', sa.Column('last_seen_camera_id', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('avg_recognition_similarity', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('profiles', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.alter_column('profiles', 'compreface_subject_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint('profiles_compreface_subject_id_key', 'profiles', type_='unique')
    op.create_index(op.f('ix_profiles_compreface_subject_id'), 'profiles', ['compreface_subject_id'], unique=True)
    op.create_index(op.f('ix_profiles_created_at'), 'profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_profiles_is_active'), 'profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_profiles_name'), 'profiles', ['name'], unique=False)
    op.add_column('watchlists', sa.Column('color', sa.String(length=7), nullable=True))
    op.add_column('watchlists', sa.Column('icon', sa.String(length=50), nullable=True))
    op.add_column('watchlists', sa.Column('enable_alerts', sa.Boolean(), nullable=True))
    op.add_column('watchlists', sa.Column('alert_on_cameras', sa.JSON(), nullable=True))
    op.add_column('watchlists', sa.Column('alert_cooldown_minutes', sa.Integer(), nullable=True))
    op.add_column('watchlists', sa.Column('webhook_url', sa.String(length=500), nullable=True))
    op.add_column('watchlists', sa.Column('webhook_enabled', sa.Boolean(), nullable=True))
    op.add_column('watchlists', sa.Column('member_count', sa.Integer(), nullable=True))
    op.add_column('watchlists', sa.Column('total_detections', sa.Integer(), nullable=True))
    op.add_column('watchlists', sa.Column('extra_metadata', sa.JSON(), nullable=True))
    op.add_column('watchlists', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_watchlists_created_at'), 'watchlists', ['created_at'], unique=False)
    op.create_index(op.f('ix_watchlists_is_active'), 'watchlists', ['is_active'], unique=False)
    op.create_index(op.f('ix_watchlists_name'), 'watchlists', ['name'], unique=True)
    op.add_column('webhooks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('webhooks', sa.Column('method', sa.String(length=10), nullable=True))
    op.add_column('webhooks', sa.Column('auth_type', sa.String(length=50), nullable=True))
    op.add_column('webhooks', sa.Column('auth_header', sa.String(length=100), nullable=True))
    op.add_column('webhooks', sa.Column('auth_value', sa.Text(), nullable=True))
    op.add_column('webhooks', sa.Column('camera_ids', sa.JSON(), nullable=True))
    op.add_column('webhooks', sa.Column('watchlist_ids', sa.JSON(), nullable=True))
    op.add_column('webhooks', sa.Column('headers', sa.JSON(), nullable=True))
    op.add_column('webhooks', sa.Column('timeout_seconds', sa.Integer(), nullable=True))
    op.add_column('webhooks', sa.Column('retry_enabled', sa.Boolean(), nullable=True))
    op.add_column('webhooks', sa.Column('retry_max_attempts', sa.Integer(), nullable=True))
    op.add_column('webhooks', sa.Column('retry_backoff_seconds', sa.Integer(), nullable=True))
    op.add_column('webhooks', sa.Column('payload_template', sa.JSON(), nullable=True))
    op.add_column('webhooks', sa.Column('total_calls', sa.Integer(), nullable=True))
    op.add_column('webhooks', sa.Column('successful_calls', sa.Integer(), nullable=True))
    op.add_column('webhooks', sa.Column('failed_calls', sa.Integer(), nullable=True))
    op.add_column('webhooks', sa.Column('last_called_at', sa.DateTime(), nullable=True))
    op.add_column('webhooks', sa.Column('last_status_code', sa.Integer(), nullable=True))
    op.add_column('webhooks', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('webhooks', sa.Column('extra_metadata', sa.JSON(), nullable=True))
    op.add_column('webhooks', sa.Column('created_by', sa.String(length=255), nullable=True))
    op.alter_column('webhooks', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.create_index(op.f('ix_webhooks_created_at'), 'webhooks', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhooks_is_active'), 'webhooks', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhooks_is_active'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_created_at'), table_name='webhooks')
    op.alter_column('webhooks', 'url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('webhooks', 'created_by')
    op.drop_column('webhooks', 'extra_metadata')
    op.drop_column('webhooks', 'last_error')
    op.drop_column('webhooks', 'last_status_code')
    op.drop_column('webhooks', 'last_called_at')
    op.drop_column('webhooks', 'failed_calls')
    op.drop_column('webhooks', 'successful_calls')
    op.drop_column('webhooks', 'total_calls')
    op.drop_column('webhooks', 'payload_template')
    op.drop_column('webhooks', 'retry_backoff_seconds')
    op.drop_column('webhooks', 'retry_max_attempts')
    op.drop_column('webhooks', 'retry_enabled')
    op.drop_column('webhooks', 'timeout_seconds')
    op.drop_column('webhooks', 'headers')
    op.drop_column('webhooks', 'watchlist_ids')
    op.drop_column('webhooks', 'camera_ids')
    op.drop_column('webhooks', 'auth_value')
    op.drop_column('webhooks', 'auth_header')
    op.drop_column('webhooks', 'auth_type')
    op.drop_column('webhooks', 'method')
    op.drop_column('webhooks', 'description')
    op.drop_index(op.f('ix_watchlists_name'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_is_active'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_created_at'), table_name='watchlists')
    op.drop_column('watchlists', 'created_by')
    op.drop_column('watchlists', 'extra_metadata')
    op.drop_column('watchlists', 'total_detections')
    op.drop_column('watchlists', 'member_count')
    op.drop_column('watchlists', 'webhook_enabled')
    op.drop_column('watchlists', 'webhook_url')
    op.drop_column('watchlists', 'alert_cooldown_minutes')
    op.drop_column('watchlists', 'alert_on_cameras')
    op.drop_column('watchlists', 'enable_alerts')
    op.drop_column('watchlists', 'icon')
    op.drop_column('watchlists', 'color')
    op.drop_index(op.f('ix_profiles_name'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_is_active'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_created_at'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_compreface_subject_id'), table_name='profiles')
    op.create_unique_constraint('profiles_compreface_subject_id_key', 'profiles', ['compreface_subject_id'])
    op.alter_column('profiles', 'compreface_subject_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('profiles', 'created_by')
    op.drop_column('profiles', 'tags')
    op.drop_column('profiles', 'avg_recognition_similarity')
    op.drop_column('profiles', 'last_seen_camera_id')
    op.drop_column('profiles', 'last_seen_at')
    op.drop_column('profiles', 'total_detections')
    op.drop_column('profiles', 'alert_on_recognition')
    op.drop_column('profiles', 'auto_created')
    op.drop_column('profiles', 'face_encodings')
    op.drop_column('profiles', 'phone')
    op.drop_column('profiles', 'email')
    op.create_table('watchlist_profiles',
    sa.Column('watchlist_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name='watchlist_profiles_profile_id_fkey'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], name='watchlist_profiles_watchlist_id_fkey'),
    sa.PrimaryKeyConstraint('watchlist_id', 'profile_id', name='watchlist_profiles_pkey')
    )
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('webhook_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='webhook_deliveries_event_id_fkey'),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], name='webhook_deliveries_webhook_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='webhook_deliveries_pkey')
    )
    op.drop_table('watchlist_members')
    op.drop_index(op.f('ix_person_events_subject'), table_name='person_events')
    op.drop_index(op.f('ix_person_events_profile_id'), table_name='person_events')
    op.drop_index(op.f('ix_person_events_created_at'), table_name='person_events')
    op.drop_index(op.f('ix_person_events_camera_id'), table_name='person_events')
    op.drop_index(op.f('ix_person_events_acknowledged'), table_name='person_events')
    op.drop_table('person_events')
    # ### end Alembic commands ###
